### PR TITLE
Team Re-organization

### PR DESCRIPTION
**Pull request by german-e-mas**
In this PR I address #97.

I added `team` and `advisor` tags to select the persons to show in which list.

In the **Meet the team** list, we display members with the `team` tag. Pato is shown first, then Gui.
In the new **Advisors** list, we display members with the `advisor` tag (Juli and Lucas).

ptal @basicNew and @JessicaJackson 

Here is a (long) screenshot of the full page:
fullpage

### CODE REVIEW

**Comment by basicNew** [comment]
I feels a little weird that Julian is listed as an adviser but his bio starts with "Julian is the founder of Ekumen". I'm not saying to remove it, but maybe word it different? Or say that he is on sabbatical on other endeavours? @JessicaJackson @manzato @patricioreyna @adamantivm (if you are reading mail) thoughts?

**Comment by manzato** [comment]
hm, I feel you @basicNew . I'd like @adamantivm 's input here too, but I think something like "Julian is the founder and former CEO of Ekumen" might work a bit better without changing the facts.

**Comment by german-e-mas** [comment]
Thanks for the comments @basicNew and @manzato . I like @manzato 's modification, and I think it works well until we have an updated bio. Should I apply this change?

> Julian is the founder and former CEO of Ekumen. Throughout his 15+ years of experience he has led many challenging, first-of-their-kind software projects to successful completion.

**Comment by JessicaJackson** [comment]
Please do, German. LGTM

**Comment by german-e-mas** [comment]
Thank you @JessicaJackson ! I modified the bio. I'll proceed to merge this now.

**Pull request merged**
