### PR TITLE
pics update

### PR DESCRIPTION
**Pull request by gecofernando**
Added Jessica to 'Team'
Updated Javier's, Michel's and Ernesto's pictures.
Changed Home page pictures.
Minor modification to Job ad

### CODE REVIEW

**Comment by adamantivm** [comment]
Hmm ... I disagree with the change to the images of expertise areas. Was there a discussion and consensus / approval on this that I missed?

**Comment by adamantivm** [comment]
@manzato what do you think?

**Comment by JessicaJackson** [comment]
Julian, see https://github.com/ekumenlabs/office-management/issues/73

**Comment by manzato** [comment]
I like the image change from 9 to 11 (9 should be removed in this PR) in the carousel.

**Comment by adamantivm** [comment]
Thanks @JessicaJackson . I also like the change from 9 to 11 and agree 9 should be removed.

I disagree with the change on drone and robot though. I think the current pictures display the concepts we want to show better.

**Comment by JessicaJackson** [comment]
I'm ok with leaving the Savibot on the left. Fer, I'm recalling that we talked about cropping it differently or  finding a different shot, so it didn't look like a computer screen. What about this one? http://www.popsci.com/bring-boring-robots
The above is an official Savioke photo of relay (repeated on the Savioke blog) but already cropped above.
Or this one?
http://static1.squarespace.com/static/53c76fe9e4b029b1ad4a55b6/55fd888ae4b01421190a49cf/55fd8aa7e4b0d8d207e4845d/1442679784706/Realy+lid+opening.jpg?format=750w
Or any others from the Savioke blog? 
http://www.savioke.com/blog/

**Comment by adamantivm** [comment]
May I suggest splitting this PR between the BIO updates and the other, more polemic, updates?

**Comment by gecofernando** [comment]
It´s fine by me. Do I need to do sth? Or can you just discard part of it and leave the rest_

**Comment by adamantivm** [comment]
You may need to do a bit of git fiddling to drop the unwanted changes. It may be easier to start over and re-apply the changes to the bios if that's easier for you.
In the future, it  is a good idea to do commits for each functional unit, so that in cases like this it becomes easier to just choose one commit and discard / undo another.

**Comment by gecofernando** [comment]
I think the 4 pics changes are un-done now. Could you check that?

**Pull request closed without merging**
