### PR TITLE
Scroll-down button removed

### PR DESCRIPTION
**Pull request by tul1**
This is a small one. It follows the following issue: https://github.com/ekumenlabs/ekumenlabs.github.io/issues/165

### CODE REVIEW

**Comment by tul1** [comment]
@german-e-mas could review this one?
Thanks :-)

**Comment by tul1** [comment]
It looks clearer now!

image

**Comment by german-e-mas** [comment]
Take a look at the `main.js` file. I believe the last function in it was related to the scroll (providing an animation to scroll smoothly). Check if it's being used somewhere else. If it's not, we can remove it.

**Comment by tul1** [comment]
Done @german-e-mas ready for a new review :-)

**Pull request merged**
