### PR TITLE
url update

### PR DESCRIPTION
**Pull request by gecofernando**
Changed  UAV's url

### CODE REVIEW

**Comment by adamantivm** [comment]
@gecofernando are you sure this is it? I don't see the old "URL" (file?) being deleted and I don't see where the link to the old page has been changed to reference the new one.

**Comment by gecofernando** [comment]
There was no file being deleted. It was a modification in the name. Unless it generates a duplicate (I believe it shouldn't) it should be ok.
The URL will respond to the file name.

**Comment by tulku** [comment]
@gecofernando have you run middleman locally with this change?

**Comment by adamantivm** [comment]
@gecofernando I see. It is probably a git issue. You probably need to tell git about the name change, which is normally through add of the old file and delete of the new (or a git mv command). May I suggest you get help from a git expert locally at HQ to look at your local repo and see if you missed something in the commit?

**Comment by gecofernando** [comment]
I did run middleman and it worked. Now there something seems to have happened and I lost the whole file.
I'll go back to before the changes and try again.

**Comment by gecofernando** [comment]
Please cancel this PR. I can't find the option to do it.

**Comment by adamantivm** [comment]
you just did

**Pull request closed without merging**
