### PR TITLE
Team pic

### PR DESCRIPTION
**Pull request by gecofernando**
New team pic

### CODE REVIEW

**Comment by basicNew** [comment]
@gecofernando in case I'm not there for the next team pic, would you let me know when you are doing it and take a notebook where I can hangout? We could even put the notebook on top of a turtlebot. It really sucks not to be there.

**Comment by gecofernando** [comment]
I honestly and not jokingly thought of photoshoping your face into Patricio2's body. But I don't have a pic with similar enough lighting.

**Comment by basicNew** [comment]
Ha, that would require quite some work :). Anyway, just consider it for future pictures (and also include the other remotes :))

**Comment by adamantivm** [comment]
@gecofernando next time plz send a single PR with all the commits, not three concatenated PRs.

**Pull request merged**
