### PR TITLE
Added iRobot to clients

### PR DESCRIPTION
**Pull request by gecofernando**
Removed Celery from clients and added iRobots

### CODE REVIEW

**Comment by adamantivm** [comment]
@gecofernando it's 140kb. Does it need to be this large? The others seem between 1 and 2 orders of magnitude smaller.

**Comment by gecofernando** [comment]
Gosh. That happens when you trust Ubuntu to edit images. I'll fix it! Sorry!

**Comment by gecofernando** [comment]
Fixed.

**Comment by adamantivm** [comment]
@tulku @manzato @patricioreyna @manzato are you OK with this swap as opposed to adding?

**Comment by manzato** [comment]
Adding is always nicer IMHO, but wouldn't want to keep C64 forever either. If we can keep it (without it being a UI mess) I'd rather keep it, but won't cry if Celery is removed.

**Comment by tulku** [comment]
I already mentioned in the issue that I would not remove clients, but if it is impossible to add without removing then I'd rather have iRobot before Celery

**Comment by patricioreyna** [comment]
+1 to Ungui and Tulku comments above. Plan B: let's swap

**Comment by gecofernando** [comment]
I created a new PR adding iRobot without taking away Celery.

**Pull request closed without merging**
